  test:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          # trigger the tests here
          echo 'Running unit tests'
          # Install all dependencies (including dependencies for running tests)
          pip3 install -r requirements.txt
          pip3 install -r ./tests/requirements.txt       
          # Discover and run unit tests in the 'tests/unit' directory
          python3 -m pytest tests/unit -v

          integration-test:
  if: github.ref == 'refs/heads/main'
  needs: [deploy-testing]
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - run: |
        # trigger the integration tests here
        echo 'Running integration tests'
        # Install all dependencies (including dependencies for running tests)
        pip3 install -r requirements.txt 
        pip3 install -r ./tests/requirements.txt 
        # Discover and run integration tests in the 'tests/integration' directory
        python3 -m pytest tests/integration -v
